avatar: /images/avatar.webp # 网站 Logo
background: # 既是博客的背景，又是文章默认头图
    path: /images/background.webp
    width: 1280
    height: 726
favicon:
  href: /favicon.ico # 网站图标
  type: image/x-icon # 图标类型，可能的值有(image/png, image/vnd.microsoft.icon, image/x-icon, image/gif)

function: # 功能开关，可选值（true,false）
  globalToc: true # 开启该功能会自动开启文章 TOC（文章目录） 功能
  wordCount: true # 是否开启文章字数统计 (true, false)
  copyCode: true # 是否允许复制代码块

imageCDN: # 图片 CDN 功能
  enable: false # 开启该功能  
  origin: /../../images/ # 图片原始目录
  to: https://cdn.jsdelivr.net/gh/nexmoe/nexmoe.github.io@latest/images/ # 图片 CDN 域名

# 自定义样式，启用后可在站点的source文件夹下新建custom.css自定义站点样式
customStyles:
  - custom.css
  
# 附加图标库 使用说明：https://docs.nexmoe.com/config/icon
iconlib: # //at.alicdn.com/t/font_1038733_0xvrvpg9c0r.css

menu:
    回到首页:
        - /
        - icon-home
    文章归档:
        - /post/archives/
        - icon-container
    下载:
        - https://example.com/
        - icon-container
    常用链接:
        - /post/favorites/
        - icon-unorderedlist
    GithubStars:
        - /post/github-project-stars/
        - icon-github
    给我赞助:
        - /post/donate/
        - icon-coffee
    关于博主:
        - /post/about/
        - icon-info-circle

widgets:
    - name: search
      enable: true
      options: 
        search: 
            type: engine # 可选engine（用搜索引擎搜索）、swiftype、或local（本地搜索）
            url: https://cn.bing.com/search?q=site:example.com # 搜索引擎地址，在type为swiftype时无效 e.g:https://www.google.com/search?q={你的博客链接}
            id: <swiftype-id> # swiftype的id，见启用教程。在type为engine时无效
    - name: social
      enable: true
      options: 
        social:
            QQ群:
                - http://qm.qq.com/cgi-bin/qm/qr?_wv=1027&k=weD8TANNWdCOveAMcdmoAxOKt5owKkDS
                - icon-QQ
                - rgb(249, 174, 8)
                - rgba(249, 174, 8, .1)
            #哔哩哔哩:
            #    - https://space.bilibili.com/20238211
            #    - icon-bilibili
            #    - rgb(231, 106, 141)
            #    - rgba(231, 106, 141, .1)
            GitHub:
                - https://github.com/margrop/
                - icon-github
                - rgb(25, 23, 23)
                - rgba(25, 23, 23, .1)
            #知乎:
            #    - https://www.zhihu.com/people/nexmoe
            #    - icon-zhihu
            #    - rgb(30, 136, 229)
            #    - rgba(30, 136, 229, .1)
            #Twitter:
            #    - https://twitter.com/dennis_1125
            #    - icon-twitter
            #    - rgb(59, 151, 239)
            #    - rgba(59, 151, 239, .1)
            RSS:
                - /atom.xml
                - icon-rss
                - rgb(247, 132, 34)
                - rgba(247, 132, 34, .1)
    - name: category
      enable: true
    - name: tagcloud
      enable: true
      options: 
        maxTagcloud: 17  # 标签云组件显示的标签数量，0 表示不限制
    - name: hitokoto # 一言 widget
      enable: true
      options: 
        widgetHitokoto: # 一言组件
            loading_placeholder: '🚀 获取中...' # 正在一言时的占位符
            loading_error_placeholder: '🐞 获取失败...' # 加载一言失败时的占位符
            category: # 一言句子类型（可选），不配置的话随机获取，详见 https://developer.hitokoto.cn/sentence/#%E5%8F%A5%E5%AD%90%E7%B1%BB%E5%9E%8B-%E5%8F%82%E6%95%B0
    - name: archive #settings: widgetAchive
      enable: true
      options:
        widgetAchive: #文章归档组件
            archive_type: 'year' #按月展示还是按年展示
            show_count: true  #是否展示数量
    - name: recent_posts
      enable: true
    - name: link #settings: widgetLink
      enable: true
      options: 
        widgetLink: #链接组件
            - title: 魔都水滴Blog
              img: /images/avatar.webp
              link : https://blog.example.com/

copyTip: "著作权归作者所有。\n商业转载请联系作者获得授权，非商业转载请注明出处。\n来源：%url" # 自定义复制版权文案,使用 %url 代替当前页面URL, 修改为false禁用

slotHead: | 
  <script charset="UTF-8" id="LA_COLLECT" src="//sdk.51.la/js-sdk-pro.min.js"></script>
  <script>LA.init({id:"23bDEwNOu1L8NhV1",ck:"23bDEwNOu1L8NhV1"})</script>
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-4NGHEP8LEV"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'G-4NGHEP8LEV');
  </script>

slotFooter: | 
  <script src="https://cdn.jsdelivr.net/npm/mathjax@latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
  <script>MathJax.Hub.Config({
      tex2jax: {
          inlineMath: [ ['$','$'], ["\\(","\\)"] ],
          processEscapes: true,
          skipTags: ['script', 'noscript', 'style', 'textarea', 'pre', 'code']
      }
  });
  MathJax.Hub.Queue(function() {
      var all = MathJax.Hub.getAllJax(), i;
      for(i=0; i < all.length; i += 1) {
          all[i].SourceElement().parentNode.className += ' has-jax';
      }
  });</script>

# 自定义侧边栏尾部内容
slotSidebar: |

# 评论框插槽
slotComment: | 
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.css">
  <script src="https://cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.min.js"></script>
  <div id="gitalk-container"></div>
  <script>
    const gitalk = new Gitalk({
      clientID: 'Ov23lib2oiNKjG5B7I1N',
      clientSecret: '0a94653f17a7b9630d85b275008da4b38e0259dd',
      repo: 'margropcomment.margrop.io',      // The repository of store comments,
      owner: 'margrop',
      admin: ['margrop'],
      pagerDirection: 'last',
      id: window.location.pathname.substring(0, 49), // 使用 pathname 的前49个字符作为 id
      title: document.title,
      language: 'zh-CN', // 根据需要设置语言
      distractionFreeMode: false
    })
    gitalk.render('gitalk-container')
  </script>

slotCopyright: | 
  <strong>版权声明：</strong>本文采用 <a href="https://creativecommons.org/licenses/by-nc-sa/3.0/cn/deed.zh" target="_blank">CC BY-NC-SA 3.0 CN</a> 协议进行许可

slotArticleEnd: | 
